"""add_is_rented_to_rentals

Revision ID: 7740358bdf3b
Revises: e31b5f1c544a
Create Date: 2026-01-13 18:16:26.445112

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7740358bdf3b'
down_revision: Union[str, Sequence[str], None] = 'e31b5f1c544a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rentals', sa.Column('is_rented', sa.Boolean(), nullable=False))
    op.alter_column('rentals', 'user_worker_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('users', 'login',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'login',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('rentals', 'user_worker_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('rentals', 'is_rented')
    # ### end Alembic commands ###
